# Generated by Django 4.2 on 2023-04-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_image/')),
                ('manufacturer', models.CharField(max_length=100)),
                ('amount_in_stock', models.IntegerField()),
                ('sale', models.BooleanField()),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='vehicle_image/')),
                ('manufacturer', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('engine', models.PositiveIntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('year', models.ImageField(upload_to='')),
                ('amount_in_stock', models.IntegerField()),
                ('sale', models.BooleanField()),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
