# Generated by Django 4.2 on 2023-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accessories_vehicles_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='price',
            field=models.PositiveBigIntegerField(default=10000),
        ),
    ]
